# Site settings
title: zhangziang's blog
email: zhangang1993@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  HI,MY NAME IS ZHANG ANG,A STU FROM CHINA.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "zhangziang.github.io" # the base hostname & protocol for your site
encoding: UTF-8
timezone: Asia/Chongqing
# Build settings
markdown: redcarpet
